name = "NurseScheduling"
uuid = "92cd2c7d-a66b-49fa-9b79-6db41388eebc"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SuperEnum = "5c958174-e7d9-5990-9618-4567de4ba542"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"